### ISSUE TITLE
Accept arrow up and down as a line jump

### ISSUE THREAD

**Issue by evandrocoan** [nimatrueway/karrowswitch#2]
![image](https://user-images.githubusercontent.com/5332158/54089718-b5e78280-434a-11e9-8698-21d4f73eb62d.png)

**Comment by nimatrueway** [comment]
Hey @evandrocoan,
This issue is too complicated to process and implement, because this tools is just a key listener/emulator. Personally, I would suggest grouping windows so that you do not have this many windows in task switcher screen.
