### ISSUE TITLE
Not working on kubuntu 20.04

### ISSUE THREAD

**Issue by sebastian-ruiz** [nimatrueway/karrowswitch#3]
I tried both the latest release and compiling from source.

With the -d option it shows me the intercepted key event:

```
Intercepted key event 2, key code 105
Intercepted key event 2, key code 191
Intercepted key event 3, key code 191
Intercepted key event 3, key code 105
Intercepted key event 2, key code 115
Intercepted key event 3, key code 115
Intercepted key event 2, key code 105
...
```

However when I use the arrow keys it does what it would do normally and does not emulate ctrl+tab or ctrl+shift+tab like it should. Thank you for your help!

**Comment by sebastian-ruiz** [comment]
Could the problem be that I have remapped the ctrl and alt keys? I am using  [Kinto](https://github.com/rbreaves/kinto).

**Comment by nimatrueway** [comment]
Hi @sebastian-ruiz, I imagine Kinto only changes key-syms not key-codes ergo remapping wouldn't have any impact on this tool. I'd suggest you replace alt key codes in `karrowswitch.cpp` 142-143 with these:

```
const KeySym KEY_LEFT_ALT = 37; // LEFT_CTRL key as LEFT_ALT
const KeySym KEY_RIGHT_ALT = 105;  // RIGHT_CTRL key as RIGHT_ALT
```

**Comment by sebastian-ruiz** [comment]
I edited the script on line 142 to `const KeySym KEY_LEFT_ALT = 105;` where key with code 105 is my 'ctrl' key.
However I now get the following output:
```
➜ ./karrowswitch -d
Intercepted key event 3, key code 36
Intercepted key event 2, key code 105
Alt has been pressed [state=1].
Intercepted key event 2, key code 191
Intercepted key event 3, key code 191
Intercepted key event 3, key code 105
Alt has been released [state=0].
Intercepted key event 2, key code 115
Intercepted key event 3, key code 115
Intercepted key event 2, key code 105
Alt has been pressed [state=1].
```
What happens is that I press ctrl+tab, then let go of tab (but not my ctrl key). Then when I press the arrow key the script thinks that I let go and pressed the ctrl key as well? I changed the script back to the default value for KEY_LEFT_ALT and the same thing happens. 

See here for log with KEY_LEFT_ALT=64:
```
Intercepted key event 3, key code 36
Intercepted key event 2, key code 64
Alt has been pressed [state=1].
Intercepted key event 3, key code 64
Alt has been released [state=0].
Intercepted key event 2, key code 105
Intercepted key event 2, key code 114
Intercepted key event 3, key code 114
^[[1;5CIntercepted key event 2, key code 64
Alt has been pressed [state=1].
```

**Comment by nimatrueway** [comment]
In your debug output I don't see `key code 23` (tab)? karrowswitch needs you to pop `alt+tab` window before it processes arrow keys (that's how windows/gnome task switcher work).

See one example:

```
Intercepted key event 2, key code 64  // alt down
Alt has been pressed [state=1].       // state = alt down
Intercepted key event 2, key code 23  // tab down
Alt+Tab has been pressed [state=20].  // state = alt+tab pressed, now arrows will be processed
Intercepted key event 3, key code 23  // tab up

Intercepted key event 2, key code 114 // arrow right
Emulated Tab.
Intercepted key event 2, key code 23  // emulated tab down
Intercepted key event 3, key code 23  // emulated tab up
Intercepted key event 3, key code 114

Intercepted key event 2, key code 114 // arrow right, again
Emulated Tab.
Intercepted key event 2, key code 23
Intercepted key event 3, key code 23
Intercepted key event 3, key code 114

Intercepted key event 3, key code 64 // alt up
Alt has been released [state=0].
```
